### ISSUE TITLE
How to load plugins?

### ISSUE THREAD

**Issue by seekM** [safeeyes/safeeyes-plugins#3]
I installed safeeyes from the Ubuntu PPA. Now I'd like to write and add a plugin. Is there a place I can put my plugin such that it is automatically loaded? Or do I have to remove safeeyes, get it from the github repo, add my plugin to the plugin folder and then build from source?

**Comment by slgobinath** [comment]
Hi,
You can install it in ` ~/.config/safeeyes/plugins` directory.
A step by step guidance is added to readme now: https://github.com/safeeyes/safeeyes-plugins#installation
